### ISSUE TITLE
decode tx instructions

### ISSUE THREAD

**Issue by roccomuso** [solana-labs/solana-web3.js#1001]
does the lib support decoding instructions to know what type of program is that?
like the tx explorer does, like detecting from the programId what kind of instruction that.
I found this: https://github.com/solana-labs/explorer/blob/master/src/utils/tx.ts

Moreover, why are these deprecated?
https://github.com/solana-labs/solana-web3.js/blob/master/src/transaction.js#L621-L646

**Comment by jstarry** [comment]
> does the lib support decoding instructions to know what type of program is that?

Sort of. You can request "parsed" transactions which, if supported, will decode the instruction for you. Right now we just have support for built in programs (system, vote, stake, etc) and a few SPL programs (token, memo). You can call [`connection.getParsedConfirmedTransaction`](https://solana-labs.github.io/solana-web3.js/class/src/connection.js~Connection.html#instance-method-getParsedConfirmedTransaction) which will call the `getConfirmedTransaction` RPC API with the `"jsonParsed"` encoding parameter.

> Moreover, why are these deprecated?
https://github.com/solana-labs/solana-web3.js/blob/master/src/transaction.js#L621-L646

Heh, those should be removed at this point. They are deprecated because those methods should only exist on transaction _instructions_. Those APIs were added a long time ago before transactions consisted of multiple instructions
