### ISSUE TITLE
web3.js: Remove use of Buffer

### ISSUE THREAD

**Issue by macalinao** [solana-labs/solana-web3.js#1100]
#### Problem
Buffer isn't built for the web. Uint8Array is and saves 10kb gzipped.

#### Proposed Solution

Begin migrating code to use Uint8Array instead. Code that doesn't use Borsh should get optimized automatically.

**Comment by katopz** [comment]
Glad to hear this! node buffer shim took me almost 3 hours to make it to work for both dev and prod via `vite`. 🤷‍♂️

**Comment by mindrunner** [comment]
Is this already work in progress? I might want to have a look at this. Does anyone know how big/complex this migration gonna be?

**Comment by steveluscher** [comment]
My focus is on replacing web3.js altogether. Follow along in #1111 and in all of the new packages in the `packages/` directory.

Deprecating `Buffer` in the current API would probably take just as long as rewriting the whole thing. Backward compat is the hardest thing, because `Uint8Array` and `Buffer` behave _slightly_ differently (particularly `toString()`) and it’s impossible to know who depends on which of the peculiar behaviours.

**Comment by buffalojoec** [comment]
> Sorry for being that guy but any update on this? This prevents me to use vite before.

Unfortunately we can't save the legacy library from `Buffer`, but the new (`2.0`) release is going to be all `Uint8Array`. You can see preview release candidates here:
https://github.com/solana-labs/solana-web3.js/releases

**Comment by spirobel** [comment]
> > Sorry for being that guy but any update on this? This prevents me to use vite before.
> 
> Unfortunately we can't save the legacy library from `Buffer`, but the new (`2.0`) release is going to be all `Uint8Array`. You can see preview release candidates here: https://github.com/solana-labs/solana-web3.js/releases

can I use this in production?
I am working on my hackathon project :-0

**Comment by steveluscher** [comment]
`@solana/web3.js` from 2.0 onward is `Buffer` free.
