### ISSUE TITLE
Support the JSON key file format that `solana-keygen` uses

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#1460]
## Motivation

[The Solana CLI and docs](https://docs.solana.com/wallet-guide/file-system-wallet) use a file format which has a single secret key inside a JSON file. web3.js doesn't currently directly support these files. 

This enhancement adds `Keypair.fromFile()` to load the Solana CLI secret key files. 

## Example use case

A user is using the solana CLI to perform a task. The user has created a secret key, by default, in `~/.config/solana/id.json` and used this via Solana CLI. They then wish to use this same keypair in web3.js.

Right now the user has to work out how to do this themselves. 

This proposal makes web3.js support the Solana CLI JSON files itself.

## Details

This would work:

```
import { Keypair } from "@solana/web3.js";
import { readFile } from "fs/promises";
import path from "path";

// @ts-ignore (just because we haven't updated types yet)
Keypair.fromFile = async (filepath?: string) => {
  if (!filepath) {
    // Default value from Solana CLI
    filepath = "~/.config/solana/id.json";
  }
  if (filepath[0] === "~") {
    const home = process.env.HOME || null;
    if (home) {
      filepath = path.join(home, filepath.slice(1));
    }
  }

  const fileContents = (await readFile(filepath)).toString();
  return Keypair.fromSecretKey(Uint8Array.from(JSON.parse(fileContents)));
};

```
Then to use, just:

```
const keyPair = await Keypair.fromFile();
```

or:

```
const keyPair = await Keypair.fromFile('somefile.json');
```

or:

```
const keyPair = await Keypair.fromFile('~/code/solana/demos/steve.json');
```

**Comment by steveluscher** [comment]
One reason _not_ to do this is that `@solana/web3.js` is _supposed_ to be multiplatform (web/server/mobile) and this only works on the server.

Two thoughts:

#1 This already sort of works in Node:

```js
const SECRET_KEY_BYTES = require('/home/me/.config/solana/id.json');

const { Keypair } = require('@solana/web3.js');

console.log(Keypair.fromSecretKey(new Uint8Array(SECRET_KEY_BYTES)));
```

#2 We could offer a separate npm package of server utilities that did this kind of stuff, as wrappers around `@solana/web3.js`, so that we don't create confusing APIs that only work on a subset of web3.js' target platforms.

**Comment by mcintyre94** [comment]
I definitely agree that it'd be nice to have these sorts of helpers in a package somewhere. Would be useful for teaching too! Maybe a new repo under `solana-developers` org?

**Comment by steveluscher** [comment]
I like that idea. My hope is that _many_ such packages will spring up around the new web3.js, because its API is _so_ flexible. It would be difficult to do such a thing without hacking or subclassing the old `Keypair` class, but it's very easy to do when everything is a function that operates over some data.

**Comment by mikemaccana** [comment]
@steveluscher Want to review? https://github.com/solana-developers/node-helpers/pull/1

**Comment by nickfrosty** [comment]
@steveluscher or @mikemaccana  I recommend closing this issue since the [`@solana-developers/node-helpers`](https://www.npmjs.com/package/@solana-developers/node-helpers) package is live
