### ISSUE TITLE
Helper method to load keypair from paper wallet

### ISSUE THREAD

**Issue by jim4067** [solana-labs/solana-web3.js#1607]
## Motivation

#1562 

solana paper wallets are stored in `~/.config/solana/id.json`. Everytime I need to use the wallet I have to either declare the keypair in my project or create a helper function that loads the keypair from the path. 
```ts
const USER_KEYPAIR_PATH = homedir() + "/.config/solana/id.json";
export const signerKeypair = Keypair.fromSecretKey(
    Buffer.from(JSON.parse(readFileSync(USER_KEYPAIR_PATH, "utf-8")))
);
```

## Example use case
When working and you need a signer that does not change and you do not want to have to declare the keypair in your config files,

having a function like `loadFromFilePath(path: string)` might be nice

## Details

Could be implemented in the `Keypair` interface.

have a function `loadFromFilePath(path: string?)` for this that optionally takes in a path argument since the default Solana config location for a wallet is `config/solana/id.json` else if the user supplies an argument to this function load the wallet from the supplied location.

**Comment by buffalojoec** [comment]
Hey, check out this repo!

https://github.com/solana-developers/node-helpers

**Comment by steveluscher** [comment]
In general, a filesystem-based helper like this won't be added to the core library because it's designed to work in browser/React Native contexts that don't have filesystems.

An example of how to do this with `@solana/web3.js` 2.0 can be found here: https://github.com/solana-labs/solana-web3.js/blob/e90ed593754c4bb1a18f2c57c716746a3403f498/packages/keys/README.md?plain=1#L68-L82
