### ISSUE TITLE
[experimental] Should `responseProcessor` be async? 

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana-web3.js#1737]
At the moment, an RPC API's requests can include a `responseProcessor` that transforms the server response before it reaches the caller in the client. We use this, for instance, to ‘upgrade’ `number` to `bigint` in the Solana RPC.

Is there a reason why you should be able to supply an async response processor here?

**Comment by buffalojoec** [comment]
Making this `async` would effectively make _all_ response processor `async` right? 

I think it might be OK considering we could stick an `await Promise.all(..)` inside and people would be none the wiser?

What would it look like if you supplied something that was synchronous, though? Do you have to do any weird wrangling or just supply it?

**Comment by mcintyre94** [comment]
I'd lean toward keeping it sync for now, because if we have an async processor here then there'll be a waterfall I think: async call to RPC -> async call to process

If possible it'd be better to independently fetch whatever else you need to process it, and then combine them after independently resolving the two async calls

That wouldn't work for use cases where you need to have the response from the RPC to process it - you'd need to do your own post-processing. I think that's probably fine though? If you're doing two async calls and they must be waterfalled, then something like this seems fine:

```ts
const { something } = await rpc.doSomething()
const result = await processThing(something)
```

I think that probably makes things clearer than having an async call to `processThing` buried in the RPC. 

Pretty speculative without a concrete async use case though!

**Comment by steveluscher** [comment]
@lorisleiva, is there any merit to doing this now, while your refactor is going on?

**Comment by lorisleiva** [comment]
My next refactoring stack will give us this for free since the API plan will return executor function that accepts a transport and returns a promise of a Response.
