### ISSUE TITLE
confirmTransaction() should default to getting a recent blockhash if none is specified.

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#2067]
## Motivation

We see code like [this from web3.js users](https://github.com/deanmlittle/anchor-escrow-2024/blob/master/tests/anchor-escrow.ts#L32C3-L32C3):

```typescript
const confirmTransaction = async (
  connection: Connection,
  signature: string
): Promise<string> => {
  const block = await connection.getLatestBlockhash();
  await connection.confirmTransaction({
    signature,
    ...block,
  });
  return signature;
};
```

And all confirmations are done through this custom function.

It would be good to add a default  `TransactionConfirmationStrategy` that fetches a recent block hash and uses it as a a `BlockheightBasedTransactionConfirmationStrategy`.

### Before:

```
const confirmTransaction = async (
  connection: Connection,
  signature: string
): Promise<string> => {
  const block = await connection.getLatestBlockhash();
  await connection.confirmTransaction({
    signature,
    ...block,
  });
  return signature;
};
```

then

```
await confirmTransaction(connection, signature)
```

### After

Just:

```
await connection.confirmTransaction(signature)
```

## Relevant meme

![image](https://github.com/solana-labs/solana-web3.js/assets/172594/0ad99756-c40c-425e-9878-ab7050e5ce3d)

**Comment by steveluscher** [comment]
> It would be good to add a default `TransactionConfirmationStrategy` that fetches a recent block hash and uses it as a a `BlockheightBasedTransactionConfirmationStrategy`.

1. Confirming a transaction using a blockhash other than the one that was _actually_ used in the transaction will yield incorrect information, such as ‘your blockhash is now invalid’ when it's either not or it's been invalid for quite some time.
2. We already have this. It's just marked as deprecated because it's bad (ie. likely to make you wait _way_ longer for a failure when your transaction has long been invalid).

https://github.com/solana-labs/solana-web3.js/blob/b2c1b82d0da512ad485e9b81c2d9db12e3ce3588/packages/library-legacy/src/connection.ts#L3727-L3732
