### ISSUE TITLE
getScalarCodecEnum does not encode an enum to its values in bytes

### ISSUE THREAD

**Issue by lithdew** [solana-labs/solana-web3.js#2319]
`getScalarCodecEnum` does not encode an enum to its values bytes.

This issue is a follow-up from #2296.

```ts
import { getScalarEnumCodec } from "@solana/web3.js";

export enum Currency {
    sol = 3,
    like = 5,
    usdc = 9,
}

const codec = getScalarEnumCodec(Currency);
console.log(codec.encode('sol')); // Should be 0x03, got 0x00
console.log(codec.encode('like')); // Should be 0x05, got 0x01
console.log(codec.encode('usdc')); // Should be 0x09, got 0x02
```

**Comment by lorisleiva** [comment]
So I was writing a regression test and I'm no longer certain that the current behaviour is a bug.

Consider the following example:

```ts
enum ExplicitNumbers {
    Zero,
    Three = 3,
    Four,
    Size = 'six',
    Nine = 9,
    FourtyTwo = 42,
}
```

Whilst the _values_ of the enum will be kept as-is, the _keys_ of the enum is what gets stored and what allows you to have these complex mapping that otherwise wouldn't work — e.g. `"six"` cannot be encoded as a `u8`.

Even without such string literals, JavaScript values are used for more than just storing bytes and therefore, they likely will need to differ from their byte representation.

The issue is that Rust enums act differently and what comes after the equal sign is not a **value** like in JavaScript but a **discriminant** whose only purpose is to be used when storing the enum as bytes. So whilst they share the same syntax, their behaviour is different which is why some people might expect the behaviour you're suggesting here.

I'm not too sure how to solve this because I do think what you're suggesting should be possible but I don't think JavaScript enums lend themselves well to this use-case.

One solution could be to offer another helper function like `getScalarEnumWithExplicitDiscriminantsCodec` (or some much better name) that would a) throw if the provided enum contains non-numerical values and b) use the enum values as discriminants.

Wdyt?

**Comment by lorisleiva** [comment]
TIL this is valid TypeScript... 🫠

```ts
enum MyEnum {
    Zero = 42,
    One = 42,
    Two = 42
}

console.log(MyEnum);
// {
//   "42": "Two",
//   "Zero": 42,
//   "One": 42,
//   "Two": 42
// } 
```

**Comment by lithdew** [comment]
> TIL this is valid TypeScript... 🫠
> 
> ```ts
> enum MyEnum {
>     Zero = 42,
>     One = 42,
>     Two = 42
> }
> 
> console.log(MyEnum);
> // {
> //   "42": "Two",
> //   "Zero": 42,
> //   "One": 42,
> //   "Two": 42
> // } 
> ```

Yeah ... it is why I tend to avoid using enums and wanted to instead opt in for, i.e., an object for defining enum codecs. There's a talk (linked below) that goes in-depth into why they're bad.

https://www.youtube.com/watch?v=0fTdCSH_QEU
