### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by benjiqq** [solana-labs/solana-web3.js#2561]
previous issue closed after 7 days

https://github.com/solana-labs/solana-web3.js/issues/1120
https://github.com/solana-labs/solana-web3.js/issues/2461

**Comment by steveluscher** [comment]
The 2.0 line of web3.js now works with Deno. More context here: https://github.com/solana-labs/solana-web3.js/issues/2461#issuecomment-2061930941

**Comment by steveluscher** [comment]
Yes. [CodeSandbox demo](https://codesandbox.io/p/devbox/solana-web3js-and-deno-qq4294?file=%2Findex.ts%3A22%2C28&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clviirbgn00063b6e8ump0zc2%2522%252C%2522sizes%2522%253A%255B56.60220994475139%252C43.39779005524861%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clviirbgn00023b6ernu07n6r%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clviirbgn00043b6eya6338jq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clviirbgn00053b6eh8hzes6w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clviirbgn00023b6ernu07n6r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clviirbgn00013b6et4bwyw1c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clviius3g00023b6e50pbm8k2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A22%252C%2522startColumn%2522%253A28%252C%2522endLineNumber%2522%253A22%252C%2522endColumn%2522%253A28%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clviirbgn00023b6ernu07n6r%2522%252C%2522activeTabId%2522%253A%2522clviius3g00023b6e50pbm8k2%2522%257D%252C%2522clviirbgn00053b6eh8hzes6w%2522%253A%257B%2522id%2522%253A%2522clviirbgn00053b6eh8hzes6w%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clviirbgn00043b6eya6338jq%2522%253A%257B%2522id%2522%253A%2522clviirbgn00043b6eya6338jq%2522%252C%2522activeTabId%2522%253A%2522clviiv70x002x3b6etzkg7bib%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clviiv70x002x3b6etzkg7bib%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clviiv72q000ndjh4fmba87z3%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

The issue was closed because there's no plan to work on this for the 1.x line of web3.js. Indeed, the problem is in one of its dependencies, as mentioned [here](https://github.com/solana-labs/solana-web3.js/issues/2461#issuecomment-2061930941).
