### ISSUE TITLE
getMultipleAccountsInfo fetches account info even with no accounts to fetch

### ISSUE THREAD

**Issue by NotoriousPyro** [solana-labs/solana-web3.js#2757]
## Overview

I cache a lot of api data due to it not changing, e.g. lookup tables.

While refactoringmy code, I found that `getMultipleAccounts` which calls `getMultipleAccountsAndContext`, calls the api, even with an array of length 0 (`[]`).

I would not expect anything should be called if there is nothing provided to the param.

In this case, the context info not even being given for `getMultipleAccountsInfo` - so there should not be an api fetch but there is.

## Steps to reproduce
Set breakpoint in connection.getMultipleAccountsInfoAndContext

Run the following:
```
const altA = await connection.getMultipleAccountsInfoAndContext(
    []
)
```

Observe that the API was called and returned nothing other than context info.

The workaround is to do something like this:

```
const newAccountInfos = unknownAccounts.length > 0
    ? await connection.getMultipleAccountsInfo(unknownAccounts, { commitment })
    : []
```
## Description of bug

I wouldn't expect the API should be called if I asked it for nothing.

I would expect the parameter to return an empty array / undefined / null / exception such as `NoAccountInfoProvided` so that the isue can be caught more easily...

I spent an awful long time wondering why my app kept making api calls when the data was cached... And this is why.

The difference is night an day
![image](https://github.com/solana-labs/solana-web3.js/assets/706132/3d17fc2e-d83f-475a-ac54-f8a94e2ca553)

**Comment by steveluscher** [comment]
This is a great find! It's not something that I think we'll add to the core library though.

Adding such an ‘empty collection’ check adds a _lot_ of complexity to the library for something that you could otherwise just do in your app – as you've done.

For instance, in the new web3.js every RPC call essentially passes params straight through the JS API without modification. This is how we are able to keep the library so small. In order to add empty collection checks, we'd have to:

* bundle an allowlist of methods that need empty collection checks applied
* for each of those, specify the path(s) of the collections that need to be checked (eg. ‘first param, or ’second param, `foo` property)
* bundle an implementation of what to do when encountering an empty collection (ie. return `[]` immediately)
* figure out what to do with callers that _expect_ the response to unconditionally contain a `context` object.

The gain here comes at too high a cost from the library API's perspective.

My recommendation is not to call the RPC if you have nothing to fetch.
