### ISSUE TITLE
IsCurrentConnectionStillActive() incorrectly returns true

### ISSUE THREAD

**Issue by enjojoy** [solana-labs/solana-web3.js#3602]
## Overview

Issue is described in detail here https://github.com/trezor/trezor-suite/issues/12628

Especially this comment https://github.com/trezor/trezor-suite/issues/12628#issuecomment-2455002572

Please implement this todo as soon as possible https://github.com/solana-labs/solana-web3.js/blob/e3459377d3cef03d6e2570119dd45ce38fc8476b/src/connection.ts#L6316

**Comment by steveluscher** [comment]
We won't be making this change, for a host of reasons. The major one is that a retry limit would forever halt reconnection attempts in such a way that your application would never learn about, because there is no way to throw errors back up to the subscription callsite. This subscriptions API is terminally flawed in this way, and we've completely rewritten it in `@solana/web3.js` version 2.0.

I'd be happy to send you a pull request to update your app to the new library.

https://github.com/trezor/trezor-suite/issues/12628#issuecomment-2487742794
