### ISSUE TITLE
add signer interface

### ISSUE THREAD

**Issue by pynixwang** [solana-labs/solana-web3.js#3653]
export a `signer` interface for third party libraries unified api

do not care keypair or wallet adapter.

**Comment by steveluscher** [comment]
I need more information. What is it that you would like beyond the types that we already export (eg. `TransactionSigner`, `MessageSigner`, `TransactionSendingSigner`, etc.).

**Comment by pynixwang** [comment]
a unified Signer
```

**Comment by pynixwang** [comment]
a unified `Signer` interface

**Comment by pynixwang** [comment]
https://github.com/solana-labs/solana-program-library/blob/d544111b4cc193394b9bb00ac3e1482bb08a5fa0/token/js/src/actions/createMint.ts#L21

`createMint` has `payer: Signer` parameter, but it must be a `Keypair`, wallet adapter is not possible.

**Comment by steveluscher** [comment]
I'm not sure that I understand the premise.

`Signer` is defined as follows:

https://github.com/solana-labs/solana-web3.js/blob/maintenance/v1.x/src/keypair.ts#L7-L10

The body of that `createMint` function uses `payer` in two positions, one at which it accesses `payer.publicKey` and another where it's used in a position that expects `Array<Signer>`.

Perhaps you'll have more luck debugging your program by posting a question on Stack Exchange.

Other than that, I encourage you to [explore the new 2.0 library](https://github.com/solana-labs/solana-web3.js/tree/master/examples/react-app). The 1.0 library about which this issue was filed will be end-of-lifed next year.
