### ISSUE TITLE
requestAirdrop() with 'finalized' seems to return before transaction is finalized (airdropFactory() is fine)

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-web3.js#3683]
## Overview

`requestAirdrop()` with 'finalized' seems to return before transaction is finalized (airdropFactory() is fine). 

Code to reproduce is below.

### Fails:

```typescript name=fails.ts
import {
  createDefaultRpcTransport,
  createSolanaRpcFromTransport,
  generateKeyPair,
  getAddressFromPublicKey,
  lamports,
} from "@solana/web3.js";

const user = await generateKeyPair();

const SOL = 1_000_000_000n;

const transport = createDefaultRpcTransport({
  url: "http://localhost:8899",
});

// Create an RPC client using that transport.
const rpc = createSolanaRpcFromTransport(transport);

const address = await getAddressFromPublicKey(user.publicKey);

const amount = lamports(1n * SOL);

const airdropTransactionSignature = await rpc
  .requestAirdrop(address, amount, { commitment: "finalized" })
  .send();
console.log("Airdrop transaction signature", airdropTransactionSignature);

console.log("Getting balance for address", address);

const getBalanceResponse = await rpc
  .getBalance(address, { commitment: "finalized" })
  .send();

console.log("Updated balance for address", address, getBalanceResponse.value);
```

Returns:

```
Airdrop transaction signature w6uhaHSMQyssCc58sqV1KdecCJ7yJtMKj1uDG6Hj7Xr4sjo6cbURbrXjL5L4CsTKW53bd3DS8x7SwmzTLApnYFo
Getting balance for address 5hML2QkSveRRBQuu9pbm34TfoeieBVNBnRsP9Ea97jzP
Updated balance for address 5hML2QkSveRRBQuu9pbm34TfoeieBVNBnRsP9Ea97jzP 0n
```

It looks like the promise is returned before the transaction is actually finalized, and the balance is 0.

### Works

```typescript name=fails.ts
import {
  airdropFactory,
  createDefaultRpcTransport,
  createSolanaRpc,
  createSolanaRpcFromTransport,
  createSolanaRpcSubscriptions,
  generateKeyPair,
  getAddressFromPublicKey,
  lamports,
} from "@solana/web3.js";

const user = await generateKeyPair();

const SOL = 1_000_000_000n;

const rpc = createSolanaRpc("http://localhost:8899");
const rpcSubscriptions = createSolanaRpcSubscriptions("ws://localhost:8900");
const airdrop = airdropFactory({ rpc, rpcSubscriptions });

const address = await getAddressFromPublicKey(user.publicKey);

const amount = lamports(1n * SOL);

const airdropTransactionSignature = await airdrop({
  commitment: "finalized",
  recipientAddress: address,
  lamports: amount,
});

console.log("Airdrop transaction signature", airdropTransactionSignature);

console.log("Getting balance for address", address);

const getBalanceResponse = await rpc
  .getBalance(address, { commitment: "finalized" })
  .send();

console.log("Updated balance for address", address, getBalanceResponse.value);
```

Returns:

```
Airdrop transaction signature AsGDKxEuq3Fxf7vFzSQaHS5bjdE9fztcGLonsAio7DpzBojMS5gtxMBJLxxhVFWeaARr2TYnNR18HsNt2qf3D9N
Getting balance for address 86EzM5asZJiQnVxpKaqDDZte6KNoMZKry73r5XJHymAX
Updated balance for address 86EzM5asZJiQnVxpKaqDDZte6KNoMZKry73r5XJHymAX 1000000000n
```

The promise is corrected returned once the transaction is finalized and the new balance shows.

**Comment by mcintyre94** [comment]
This is just how the `requestAirdrop` RPC method works, and it's exactly why we created `airdropFactory` for v2.

If you check [the source of the RPC method](https://github.dev/anza-xyz/agave/blob/5d98c6ab576677811e2acbf76f0ad60b363bdbd4/rpc/src/rpc.rs#L3611) you'll see that the `commitment` config is used only to determine the blockhash used for the airdrop transaction. The RPC method returns the transaction signature without waiting for it to be confirmed. You can see that the commitment is not passed to the `_send_transaction` method there. 

In web3js it would be impossible to make `rpc.requestAirdrop(...)` wait for the transaction to land, because we need `rpcSubscriptions` to do that. That's why `airdropFactory` requires both of them.

I suspect that Agave's RPC layer has the same architectural limitation, and it would be infeasible to make that RPC method wait until the transaction lands before returning. AFAIK no RPC method has behaviour like that currently, anything that confirms transactions is using subscriptions.

**Comment by mikemaccana** [comment]
@mcintyre94 got it. This may be a documentation issue - there's very little info on airdrop on https://github.com/solana-labs/solana-web3.js/ and searching for the topic only gives `rpc.requestAirdrop()`.
