### ISSUE TITLE
npm package version 0.33.0 downloads different bpf-sdk versions

### ISSUE THREAD

**Issue by vkomenda** [solana-labs/solana-web3.js#719]
Due to some npm oddity different bpf-sdk versions are downloaded. Both `example-tictactoe` and `example-token` depend on
```
"@solana/web3.js": "^0.33.0"
```
However
```
example-token/node_modules/@solana/web3.js/bpf-sdk$ cat version.txt 
1.0.4
c35f4927cd2621eb3f76572f67b7f19317021441
```
and
```
example-tictactoe/node_modules/@solana/web3.js/bpf-sdk$ cat version.txt 
1.1.0
fd00e5cb35d5977aa05aff198850a747177a45ca
```
which means that the former installs Rust-BPF v0.2.1 and the latter v0.2.2.

Perhaps the npm package number should be incremented?

**Comment by jstarry** [comment]
Hey there @vkomenda!

Thanks for calling this out, we definitely need to improve this!

Right now, as you've noted, the web3 sdk is not tied to a particular bpf-sdk version. Instead, it's tied to a particular bpf-sdk release channel ("stable", "beta", or "edge"). This channel can be specified by setting the `"testnetDefaultChannel"` property in the project's `package.json`. Since `example-token` doesn't specify this property, it falls back to what is set for `@solana/web3.js` which is `"edge"`.

The bpf-sdk is removed and auto-updated every time `npm install` is ran (which I personally find to be very annoying). So this is how you ended up with a newer version of the bpf-sdk.

I think there are a few action items to pull out here:
1. bpf-sdk should have versioned releases
2. Tie the bpf-sdk version to the web3 sdk npm module
3. Make the bpf-sdk update process less surprising
  - check if update is available before clearing previously installed version
  - add a console message like "web3 sdk vX.X requires bpf-sdk version vX.X"

Anything else? cc @jackcmay 

Also, I think that using web3 sdk as a delivery mechanism for the bpf-sdk is a little wonky to begin with. Devs don't need the web3 sdk for writing Solana BPF programs. I would prefer the bpf sdk to be managed separately.

**Comment by jackcmay** [comment]
@vkomenda 

The bpf-sdk releases are versioned, check out the example's release branchs v1.0. 
The bpf-sdk version is not tied to the web3 version.  Instead, the bpf-sdk version is tied to the Solana localnet version so that the API/ABI's are matched.

Also, different examples or branches may download different versions of the bpf-sdk.  In the case of token, we don't have a release branch and should be on whatever is specified in `testnetDefaultChannel` for both localnet and bpf-sdk.  Tictactoe, on the other hand, depends on what branch you are on.  If you are on the master branch you should be picking up bpf-sdk edge whereas if you are on the v1.0 branch you should be picking up  bpf-sdk v1.0

I tried tictactoe and it appears to be behaving as I would expect.  bpf-sdk v1.0.0 on v1.0 brach and v1.1.0 on the master branch.  Token also in that its downloading beta as specified.

Does the above make sense?  If so, do you have any suggestions on how we could make this more clearly communicated or more explicit?  

For example, we could highlight the npm variable that determines the bpf-sdk version `testnetDefaultChannel` or rename it to make it more clear.

Also before the sdk is installed the script prints the following message:
`Installing v1.0.0 BPF SDK into node_modules/@solana/web3.js`.  Maybe make it more verbose about where the version is coming from?

@jstarry For #2, What did you have in mind for tieing these two versions together?

**Comment by jstarry** [comment]
@jackcmay I think we could rename `testnetDefaultChannel` to something like `solanaVersion` to improve clarity (but still allow `edge`). Then we can avoid re-installing the BPF SDK unless there is a version mismatch or if `edge` is chosen.

I've created a new issue to track this: https://github.com/solana-labs/solana-web3.js/issues/766

**Comment by jstarry** [comment]
I also created an issue to improve the BPF SDK install behavior: https://github.com/solana-labs/solana-web3.js/issues/767

**Comment by jstarry** [comment]
Closing in favour of those issues. Thanks @vkomenda for raising this concern!
