### ISSUE TITLE
Rethink `sendAndConfirm...` convenience methods

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana-web3.js#892]
The web3 sdk currently supports the following convenience methods:
* `sendAndConfirmRecentTransaction`
* `sendAndConfirmTransaction`
* `sendAndConfirmRawTransaction`

These all call the `getSignatureStatuses` RPC method which returns the cluster confirmation status for a transaction.

#### Proposed Changes
* Add `confirmations` param to `sendAndConfirmTransaction` and `sendAndConfirmRawTransaction` which maps to the `confirmations` value returned by `getSignatureStatuses`.
* Change `sendAndConfirmRecentTransaction` to call `sendAndConfirmTransaction` with `confirmations: 0`

**Comment by jstarry** [comment]
@CriesofCarrots does this sound right?

**Comment by CriesofCarrots** [comment]
> @CriesofCarrots does this sound right?

Yep, sounds right to me!

**Comment by garious** [comment]
Also, "send*Message" would be more appealing than any "send*Transaction" method. Over in the world of `BankClient`, user code never builds transactions, query for a recent blockhash, or de-dup the signers. And although this isn't implemented there, if wanted, since the client is proved the list of signers, it could resign after it determines the blockhash expired.

Besides the usability improvement, there's also performance motivation for passing the client a `Message` instead of a `Transaction`. Given a *list* of messages, each one can be sent immediately after signing.  When signing requires user approval, as is the case with a Ledger wallet, this allows the first transaction to be accepted by the cluster whereas otherwise its blockhash may expires waiting for all transactions to be signed.
