### ISSUE TITLE
Return as numbers not strings?

### ISSUE THREAD

**Issue by prographo** [solana-labs/solana-web3.js#995]
connection.getParsedProgramAccounts()

A very few numbers are returned as strings.

lockup.rentExemptReserve
delegation.activationEpoch, deactivationEpoch, stake

<img width="1156" alt="Screenshot 2020-10-24 at 14 27 58" src="https://user-images.githubusercontent.com/11575008/97082997-59130b80-1605-11eb-91c2-e31e5744f366.png">

**Comment by jstarry** [comment]
@prographo yes, this is intended because we wanted to avoid returning numbers greater than 2^53 - 1 because JavaScript doesn't handle integers in that range safely. Typically every lamport (smallest unit of SOL) will be returned as a string. `activationEpoch` and `deactivationEpoch` are interesting exceptions... They will be set as u64::MAX in certain cases so we had to return those as strings as well. To illustrate, u64::MAX is `18446744073709551615` which is represented in JS as `18446744073709552000`
